# Audit Workflow
# For app-auditor agent (Beverly Barlowe)
# Based on SAFETY-FIRST-WORKFLOW-TEMPLATE.yaml

name: audit-workflow
description: Comprehensive app auditing and validation workflow with adaptive context support
version: 1.0.0
agent_assignments:
  primary: app-auditor
  support: [frappe-compliance-validator, erpnext-architect, testing-specialist]
  verification: erpnext-qa-lead

# MANDATORY SAFETY INTEGRATION
safety_integration:
  template_base: SAFETY-FIRST-WORKFLOW-TEMPLATE.yaml
  context_detection: automatic
  panic_monitoring: active
  rollback_capability: required

stages:
  # STAGE 1: MANDATORY CONTEXT GATHERING (Cannot Skip)
  - name: context_gathering
    description: "Determine audit context and gather appropriate information"
    mandatory: true
    can_skip: false
    context_adaptive: true
    
    substages:
      - name: detect_context_type
        description: "Identify if this is troubleshooting, new development, enhancement, or migration"
        actions:
          - determine_context: ["TROUBLESHOOTING", "NEW_DEVELOPMENT", "ENHANCEMENT", "MIGRATION"]
          - log_context: "echo '## Context: [CONTEXT_TYPE] App audit' >> SESSION-CHANGELOG.md"
      
      - name: gather_context_specific_info
        description: "Collect information appropriate to context type"
        context_branches:
          TROUBLESHOOTING:
            - execute: "pwd && git status && tail -20 ../logs/frappe.log"
            - analyze: "audit failures, validation errors, quality issues"
            - document: "current audit problems and failed validations"
          
          NEW_DEVELOPMENT:
            - execute: "pwd && git status && ls -la"
            - analyze: "planned app architecture, audit requirements, quality targets"
            - document: "quality goals and audit criteria"
          
          ENHANCEMENT:
            - execute: "pwd && git status && git diff"
            - analyze: "current audit state, improvement opportunities, quality gaps"
            - document: "enhancement goals and audit improvements"
          
          MIGRATION:
            - execute: "pwd && git status"
            - analyze: "source system audit, target quality requirements"
            - document: "migration audit strategy and quality preservation"

    decision_gate:
      condition: "context_gathered AND appropriate_info_collected"
      fail_action: "RETURN_TO_CONTEXT_GATHERING"
      success_action: "PROCEED_TO_ANALYSIS"

  # STAGE 2: MANDATORY COMPREHENSIVE ANALYSIS (Cannot Skip)
  - name: comprehensive_analysis
    description: "Analyze app components and identify audit requirements"
    mandatory: true
    can_skip: false
    
    substages:
      - name: component_inventory
        description: "Catalog all app components for audit"
        actions:
          - execute_task: "audit-app-quality.md"
          - inventory_doctypes: "list all DocTypes and their configurations"
          - inventory_reports: "list all reports and dashboards"
          - inventory_pages: "list all pages and workspaces"
          - inventory_apis: "list all API endpoints and methods"
          - inventory_workflows: "list all workflows and automations"
      
      - name: dependency_analysis
        description: "Map component relationships and dependencies"
        actions:
          - map_relationships: "DocType relationships and link fields"
          - identify_dependencies: "inter-component dependencies"
          - check_consistency: "naming conventions and patterns"
      
      - name: quality_assessment
        description: "Evaluate component quality and compliance"
        context_branches:
          TROUBLESHOOTING:
            - analyze: "quality failures, compliance violations, audit errors"
            - document: "specific issues and their impact"
          
          NEW_DEVELOPMENT:
            - analyze: "quality requirements, compliance standards, audit goals"
            - document: "quality targets and measurement criteria"
          
          ENHANCEMENT:
            - analyze: "current quality state, improvement opportunities"
            - document: "quality enhancement strategy"
          
          MIGRATION:
            - analyze: "source quality state, target quality requirements"
            - document: "quality preservation and improvement plan"

    decision_gate:
      condition: "analysis_complete AND dependencies_mapped"
      fail_action: "ESCALATE_TO_ERPNEXT_ARCHITECT"
      success_action: "PROCEED_TO_PLANNING"

  # STAGE 3: MANDATORY FINDINGS DOCUMENTATION (Cannot Skip)
  - name: findings_documentation
    description: "Document audit findings and plan remediation"
    mandatory: true
    can_skip: false
    
    substages:
      - name: findings_compilation
        description: "Compile comprehensive audit findings"
        actions:
          - categorize_findings: "organize by severity and component type"
          - prioritize_issues: "rank by business impact and technical risk"
          - estimate_effort: "time and resource requirements for fixes"
      
      - name: remediation_planning
        description: "Plan fixes and improvements"
        context_branches:
          TROUBLESHOOTING:
            - plan_fixes: "specific remediation steps for audit failures"
            - design_rollback: "recovery plan if remediation fails"
          
          NEW_DEVELOPMENT:
            - plan_implementation: "quality assurance integration"
            - design_monitoring: "ongoing quality monitoring"
          
          ENHANCEMENT:
            - plan_improvements: "quality enhancement roadmap"
            - design_migration: "safe transition to improved quality"
          
          MIGRATION:
            - plan_conversion: "quality preservation strategy"
            - design_validation: "post-migration quality verification"
      
      - name: report_generation
        description: "Generate comprehensive audit report"
        actions:
          - generate_executive_summary: "high-level findings and recommendations"
          - create_detailed_report: "component-by-component analysis"
          - provide_remediation_plan: "step-by-step improvement roadmap"
          - estimate_timeline: "realistic implementation timeline"

    decision_gate:
      condition: "findings_documented AND plan_complete"
      fail_action: "REVISE_DOCUMENTATION"
      success_action: "PROCEED_TO_IMPLEMENTATION"

  # STAGE 4: CONTROLLED IMPLEMENTATION (With Panic Detection)
  - name: controlled_implementation
    description: "Execute audit recommendations with safety monitoring"
    panic_detection: true
    attempt_limit: 3
    
    substages:
      - name: pre_implementation_setup
        description: "Prepare for audit execution"
        actions:
          - initialize_changelog: "create detailed change log"
          - backup_current_state: "preserve current app state"
          - verify_tools: "ensure audit tools are ready"
      
      - name: audit_execution
        description: "Execute planned audit procedures"
        safety_checks:
          - one_component_at_time: true
          - validate_each_audit: true
          - document_findings: true
        
        actions:
          - execute_audit_procedures: "run planned audit checks"
          - monitor_progress: "track audit completion"
          - handle_failures: "manage audit failures gracefully"
      
      - name: remediation_implementation
        description: "Apply audit recommendations"
        context_branches:
          TROUBLESHOOTING:
            - apply_fixes: "implement planned remediation steps"
            - validate_fixes: "verify issues are resolved"
          
          NEW_DEVELOPMENT:
            - implement_quality_controls: "integrate quality assurance"
            - validate_implementation: "verify quality integration"
          
          ENHANCEMENT:
            - apply_improvements: "implement quality enhancements"
            - validate_improvements: "verify enhancement success"
          
          MIGRATION:
            - execute_conversion: "perform quality-preserving migration"
            - validate_migration: "verify quality preservation"

    panic_detection:
      triggers:
        - rapid_changes: "more than 3 audit attempts in 5 minutes"
        - error_spiral: "same audit checks failing repeatedly"
        - resource_exhaustion: "audit tools becoming unresponsive"
      
      response:
        immediate_action: "STOP_ALL_AUDITING"
        rollback_action: "RESTORE_BACKUP_STATE"
        escalation: "ALERT_ERPNEXT_QA_LEAD"

    decision_gate:
      condition: "audit_complete AND recommendations_implemented"
      fail_action: "INCREMENT_ATTEMPT_COUNTER"
      success_action: "PROCEED_TO_VALIDATION"

  # STAGE 5: MANDATORY VALIDATION (Cannot Skip)
  - name: validation_and_verification
    description: "Verify audit results and quality improvements"
    mandatory: true
    can_skip: false
    
    substages:
      - name: quality_verification
        description: "Verify quality improvements achieved"
        actions:
          - run_quality_checks: "comprehensive quality verification"
          - generate_quality_report: "detailed quality status"
          - measure_improvements: "quantify quality gains"
      
      - name: cross_verification
        description: "Independent verification by QA lead"
        actions:
          - request_verification: "erpnext-qa-lead review"
          - await_confirmation: "independent quality confirmation"
          - address_feedback: "resolve any identified issues"
      
      - name: documentation_completion
        description: "Complete audit documentation"
        actions:
          - finalize_changelog: "complete change documentation"
          - generate_audit_report: "comprehensive audit results"
          - update_quality_records: "maintain quality tracking"

    decision_gate:
      condition: "quality_verified AND documentation_complete"
      fail_action: "RETURN_TO_REMEDIATION"
      success_action: "WORKFLOW_COMPLETE"

# FAILURE HANDLING
failure_handling:
  third_attempt_failure:
    action: "STOP_AND_ESCALATE"
    escalation_target: "erpnext-qa-lead"
    documentation_required: true
  
  panic_mode_triggered:
    immediate_action: "EMERGENCY_STOP"
    rollback_required: true
    human_intervention: true
  
  audit_timeout:
    action: "GRACEFUL_STOP"
    documentation_required: true
    retry_strategy: "manual_review_required"

# SUCCESS CRITERIA
success_criteria:
  - audit_completeness_above_95_percent: true
  - zero_critical_quality_issues: true
  - all_recommendations_addressed: true
  - documentation_complete: true
  - cross_verification_passed: true

# INTEGRATION POINTS
integration:
  prerequisite_workflows: ["structure-validation-workflow"]
  dependent_workflows: ["quality-assurance-workflow"]
  notification_targets: ["erpnext-qa-lead", "frappe-compliance-validator"]
  
# METRICS AND MONITORING
metrics:
  track:
    - audit_completion_time
    - quality_score_improvement
    - issue_resolution_rate
    - panic_mode_incidents
    - cross_verification_success_rate
  
  alerts:
    - quality_score_below_threshold
    - repeated_audit_failures
    - panic_mode_activation
    - verification_rejection