name: bmad-erpnext-v15
version: 2.0.0
short-title: ERPNext v15 Modern App Builder
description: >-
  Complete BMAD expansion pack for building modern ERPNext v15 apps with Vue SPA frontend.
  Includes Vue 3, Frappe UI, PWA support, and comprehensive migration tools for Airtable and n8n.
author: BMAD Team
slashPrefix: bmadErpNext